site_name: 'SurgeScript Documentation'
site_url: 'https://docs.opensurge2d.org/'
site_author: 'Alexandre Martins'
site_description: 'SurgeScript is a scripting language for games.'
site_dir: 'docs_html/'
copyright: 'SurgeScript is a scripting language for games. Copyright Â© 2016-2021 Alexandre Martins.'
google_analytics: ['UA-120511928-1', 'opensurge2d.org']
repo_url: 'https://github.com/alemart/surgescript'
strict: true
theme:
    name: 'material'
nav:
    - 'Introduction': 'index.md'
    - 'Download': 'download.md'
    - 'Crash Course':
        - 'Hello, World!': 'tutorials/hello.md'
        - 'Testing your scripts': 'tutorials/testing.md'
        - 'Introduction to objects': 'tutorials/objects.md'
        - 'Variables': 'tutorials/variables.md'
        - 'Expressions': 'tutorials/expressions.md'
        - 'Conditionals': 'tutorials/conditionals.md'
        - 'Loops': 'tutorials/loops.md'
        - 'Functions': 'tutorials/functions.md'
        - 'Comments': 'tutorials/comments.md'
        - 'Tags': 'tutorials/tags.md'
        - 'Object tree': 'tutorials/object_tree.md'
        - 'Components': 'tutorials/components.md'
        - 'Properties': 'tutorials/properties.md'
        - 'Packages': 'tutorials/packages.md'
        - 'Advanced features': 'tutorials/advanced_features.md'
        - 'Best practices': 'tutorials/best_practices.md'
    - 'SurgeScript Reference':
        - 'Application': 'reference/application.md'
        - 'Arguments': 'reference/arguments.md'
        - 'Array': 'reference/array.md'
        - 'Boolean': 'reference/boolean.md'
        - 'Console': 'reference/console.md'
        - 'Date': 'reference/date.md'
        - 'Dictionary': 'reference/dictionary.md'
        - 'GC': 'reference/gc.md'
        - 'Iterator': 'reference/iterator.md'
        - 'Math': 'reference/math.md'
        - 'Number': 'reference/number.md'
        - 'Object': 'reference/object.md'
        - 'Plugin': 'reference/plugin.md'
        - 'String': 'reference/string.md'
        - 'SurgeScript': 'reference/surgescript.md'
        - 'System': 'reference/system.md'
        - 'TagSystem': 'reference/tags.md'
        - 'Time': 'reference/time.md'
    - 'SurgeEngine Reference':
        - 'Actor': 'engine/actor.md'
        - 'Animation': 'engine/animation.md'
        - 'Audio':
            - 'Music': 'engine/music.md'
            - 'Sound': 'engine/sound.md'
        - 'Behaviors':
            - 'Behavior': 'engine/behavior.md'
            - 'CircularMovement': 'engine/circular_movement.md'
            - 'DirectionalMovement': 'engine/directional_movement.md'
            - 'Enemy': 'engine/enemy.md'
            - 'Platformer': 'engine/platformer.md'
        - 'Brick': 'engine/brick.md'
        - 'Camera': 'engine/camera.md'
        - 'Collisions':
            - 'Collider': 'engine/collider.md'
            - 'CollisionBall': 'engine/collisionball.md'
            - 'CollisionBox': 'engine/collisionbox.md'
            - 'Sensor': 'engine/sensor.md'
        - 'Entity': 'engine/entity.md'
        - 'Events':
            - 'Event': 'engine/event.md'
            - 'EventList': 'engine/eventlist.md'
            - 'EventChain': 'engine/eventchain.md'
            - 'DelayedEvent': 'engine/delayedevent.md'
            - 'EntityEvent': 'engine/entityevent.md'
            - 'FunctionEvent': 'engine/functionevent.md'
        - 'Input':
            - 'Input': 'engine/input.md'
            - 'Mouse': 'engine/mouse.md'
        - 'Lang': 'engine/lang.md'
        - 'Level': 'engine/level.md'
        - 'Player': 'engine/player.md'
        - 'Prefs': 'engine/prefs.md'
        - 'SurgeEngine': 'engine/surgeengine.md'
        - 'Transform': 'engine/transform.md'
        - 'UI':
            - 'Text': 'engine/text.md'
        - 'Vector2': 'engine/vector2.md'
        - 'Video':
            - 'Screen': 'engine/screen.md'
        - 'Web': 'engine/web.md'
